### ISSUE TITLE
KIP contract bug 

### ISSUE THREAD

**Issue by JayChoi1736** [klaytn/klaytn-contracts#19]
**Describe the bug**
i found that KIP37.sol in klaytn-contracts does not support KIP37 interface.
it seems from missing of totalSupply function
formal interfaceID is calculated by
/*
     *     bytes4(keccak256(‘balanceOf(address,uint256)’)) == 0x00fdd58e
     *     bytes4(keccak256(‘balanceOfBatch(address[],uint256[])’)) == 0x4e1273f4
     *     bytes4(keccak256(‘setApprovalForAll(address,bool)’)) == 0xa22cb465
     *     bytes4(keccak256(‘isApprovedForAll(address,address)’)) == 0xe985e9c5
     *     bytes4(keccak256(‘safeTransferFrom(address,address,uint256,uint256,bytes)’)) == 0xf242432a
     *     bytes4(keccak256(‘safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)’)) == 0x2eb2c2d6
     *     bytes4(keccak256(‘totalSupply(uint256)’)) == 0xbd85b039
     *
     *     => 0x00fdd58e ^ 0x4e1273f4 ^ 0xa22cb465 ^
     *        0xe985e9c5 ^ 0xf242432a ^ 0x2eb2c2d6 ^ 0xbd85b039 == 0x6433ca1f
     */
but totalSupply function is moved to preset/KIP37Supply.sol
so,

`interfaceId == type(IKIP37).interfaceId` 
in https://github.com/klaytn/klaytn-contracts/blob/master/contracts/KIP/token/KIP37/KIP37.sol#L45-L49
does not match with the formal interfaceId.

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
 - The version pragma of the smart contract(s) involved
 - OS and its version [e.g. macOS/10.14]

**Additional context**

**Comment by naveed-klaytn** [comment]
Hi @JayChoi1736 thank you for highlighting this issue.

I can confirm the implemented IKIP37's interfaceId is `0xd9b67a26` while the standard [KIP37](https://kips.klaytn.foundation/KIPs/kip-37#kip37-interface)'s interfaceId was `0x6433ca1f`. That's why `interfaceId == type(IKIP37).interfaceId` returns false

It is because (as you've mentioned) of skipping `totalSupply(uint256)` function from [IKIP37.sol](https://github.com/klaytn/klaytn-contracts/blob/master/contracts/KIP/token/KIP37/IKIP37.sol)

So there are two ways to fix this issue

1. Declare `totalSupply(uint256)` function in [IKIP37.sol](https://github.com/klaytn/klaytn-contracts/blob/master/contracts/KIP/token/KIP37/IKIP37.sol) & implementing it in [KIP37.sol](https://github.com/klaytn/klaytn-contracts/blob/master/contracts/KIP/token/KIP37/KIP37.sol) (as per [KIP37](https://kips.klaytn.foundation/KIPs/kip-37#kip37-interface) standard)
  1.1. In this case I would suggest to merge [KIP32Supply.sol](https://github.com/klaytn/klaytn-contracts/blob/master/contracts/KIP/token/KIP37/extensions/KIP37Supply.sol) with KIP37.sol
2. Update [KIP37](https://kips.klaytn.foundation/KIPs/kip-37#kip37-interface) to remove `totalSupply(uint256)` function from its interface and set its formal interfaceID `0xd9b67a26`

@toniya-klaytn please suggest with which option I should proceed

**Comment by 0xxlegolas** [comment]
@JayChoi1736  , You are right Formal interface id is : 0x6433ca1f. 
When we forked contracts from openzepplien (oz), we want to follow the [oz standard](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/extensions/ERC1155Supply.sol#L22) in contracts. However this breaks the KIP standard. 

We can fix this by Declaring totalSupply(uint256) function in KIP37.sol as per the standard.
